
export const CARD_PRICE_FLOOR_FILTER = 4;
export const CARD_WEIGHT_FLOOR_FILTER = 0;
export const GLOBAL_DROP_RATE = 7954753;
export const AREA_LEVEL = 83;
export const USE_FORCE_REMOVE_FILTER = true;
export const USE_FORCE_SHOW_FILTER = true;
export const FORCE_REMOVE_V_FILTER = new Set([]);
export const FORCE_REMOVE_FILTER = new Set([
  'The Easy Stroll',
  'Three Faces in the Dark',
  'The Lunaris Priestess',
  'The Explorer',
  'The Mountain',
  'Boundless Realms',
  'Azure Rage',
  'Left to Fate',
  'Might is Right',
  'Scholar of the Seas',
  'Grave Knowledge',
  'The Wolverine',
  'Blind Venture',
  "Hunter's Resolve",
  "Alivia's Grace",
  'The Admirer',
  'The Surgeon',
  "The Wolf's Shadow",
  'Shard of Fate',
  'Jack in the Box',
  'Last Hope',
  'Mitts',
  'The Battle Born',
  'The Sun',
  'The Demoness',
  'The Sigil',
  'The Twins',
  'The Inoculated',
  'The Army of Blood',
  'The Visionary',
  'The Gladiator',
  "Gemcutter's Promise",
  'The Web',
  "The Sword King's Salute",
  'Boon of Justice',
  'The Penitent',
  'The Warden',
  'The Cache',
  "Lysah's Respite",
  'The Fathomless Depths',
  'The Harvester',
  'The Fox',
  'Volatile Power',
  'The Endurance',
  'The Wolf',
  'Time-Lost Relic',
  'The Rite of Elements',
  'Gift of the Gemling Queen',
  'The Standoff',
  'Prosperity',
  'Heterochromia',
  'The Insatiable',
  'The Incantation',
  'The Betrayal',
  'The Pack Leader',
  'The Oath',
  'Vile Power',
  'The Surveyor',
  'Thunderous Skies',
  'The Tower',
  'The Stormcaller',
  'The Opulent',
  'The Blazing Fire',
  'The Journalist',
  "The Jeweller's Boon",
  'The Survivalist',
  'Glimmer of Hope',
  'Destined to Crumble',
  'The Scholar',
  'Thirst for Knowledge',
  "Emperor's Luck",
  'Loyalty',
  'A Sea of Blue',
  'The Lover',
  "The King's Blade",
  'The Catalyst',
  "Lantador's Lost Love",
  'The Scarred Meadow',
  'Rats',
  'The Witch',
  'Three Voices',
  "The Dragon's Heart",
    'Cursed Words',
  'Terrible Secret of Space'
]);
export const FORCE_SHOW_FILTER = new Set([
  'The Primordial',
  'Coveted Possession',
  'The Chains that Bind',
  'The Union',
  'The Wrath',
  'No Traces',
  'Lingering Remnants',
  "Bowyer's Dream",
  'Draped in Dreams',
  'Immortal Resolve',
  'The Celestial Justicar',
  'The Porcupine',
  'The Innocent',
]);
export const REAL_CARD_RATE = { name: 'The Union', number: 38 };
export const PINNED_DPI = 61482.640295231180216993095674228;
