export const maps = [
    "ForbiddenWoods",
    "ColdRiver",
    "FrozenCabins",
    // "Summit",
    "Iceberg",
    "Scriptorium",
    "Museum",
    "Academy",
    "DrySea",
    "Dunes",
    "DesertSpring",
    // "Desert",
    "MineralPools",
    "CrystalOre",
    "TortureChamber",
    "Grotto",
    "Wharf",
    "FloodedMine",
    "Waterways",
    "Vault",
    // "Coves",
    "Peninsula",
    "Geode",
    "AshenWood",
    "SpiderForest",
    "Lair",
    "Thicket",
    // "DarkForest",
    "TropicalIsland",
    // "Ramparts",
    "Stagnation",
    "JungleValley",
    "BrambleValley",
    "SunkenCity",
    // "AncientCity",
    "VaalPyramid",
    "Alleyways",
    // "Bazaar",
    "Arcade",
    "Port",
    "MoonTemple",
    "Factory",
    // "RelicChambers",
    // "Laboratory",
    // "Dig",
    "Excavation",
    "Orchard",
    "Plaza",
    // "Chateau",
    "Conservatory",
    "Temple",
    "Cemetery",
    "GraveTrough",
    "Graveyard",
    "LavaChamber",
    "BoneCrypt",
    "Bog",
    // "MudGeyser",
    "Marshes",
    "Basilica",
    "Residence",
    "Arsenal",
    // "Colonnade",
    // "Ghetto",
    "Promenade",
    // "Precinct",
    // "OvergrownRuin",
    "OvergrownShrine",
    // "Core",
    "Courtyard",
    "Terrace",
    "Gardens",
    "Strand",
    // "Caldera",
    "Shore",
    "LavaLake",
    "Estuary",
    "Volcano",
    "Foundry",
    "UndergroundSea",
    "CursedCrypt",
    "Necropolis",
    "AcidLakes",
    "ArachnidNest",
    "ArachnidTomb",
    "AridLake",
    "Armoury",
    "Atoll",
    "Barrows",
    "Beach",
    "Belfry",
    "BurialChambers",
    "Cage",
    "Canyon",
    // "Carcass",
    "CastleRuins",
    "Cells",
    "Channel",
    "CitySquare",
    // "Colosseum",
    "CoralRuins",
    "Courthouse",
    // "Tribunal",
    "CrimsonTemple",
    "CrimsonTownship",
    "DefiledCathedral",
    "Dungeon",
    "Fields",
    "ForkingRiver",
    "Springs",
    "HauntedMansion",
    // "InfestedValley",
    // "IvoryTemple",
    "Leyline",
    "Lighthouse",
    "Lookout",
    "Malformation",
    "Mausoleum",
    "Maze",
    // "Mesa",
    "Palace",
    "Park",
    "Pen",
    "Phantasmagoria",
    "Pier",
    "Pit",
    "Plateau",
    "PrimordialPool",
    // "Racecourse",
    "Reef",
    // "Sepulchre",
    "Shipyard",
    "Shrine",
    "Siege",
    "Silo",
    // "SpiderLair",
    "SulphurVents",
    "Tower",
    "ToxicSewer",
    "UndergroundRiver",
    "VaalTemple",
    "Villa",
    "WastePool",
    "Wasteland",
  ];
  